# Generated by Django 2.2.1 on 2021-06-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('ssex', models.BooleanField(default=0)),
                ('sage', models.IntegerField()),
                ('sdept', models.CharField(max_length=20)),
                ('smajor', models.CharField(max_length=20)),
                ('sgrade', models.CharField(max_length=20)),
                ('stype', models.CharField(max_length=20)),
                ('sintime', models.DateField()),
                ('souttime', models.DateField()),
            ],
        ),
    ]
