# Generated by Django 2.2.1 on 2021-07-01 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sushe_num', models.CharField(max_length=30)),
                ('louhao', models.CharField(max_length=20)),
                ('quhao', models.CharField(max_length=10)),
                ('cenghao', models.CharField(max_length=20)),
                ('sushehao', models.CharField(max_length=20)),
                ('max_occupancy', models.IntegerField()),
                ('occupancy', models.IntegerField()),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=100)),
                ('data', models.DateField()),
                ('people', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.FloatField()),
                ('yongshuiliang', models.IntegerField()),
                ('yongdianliang', models.IntegerField()),
                ('sushe_num', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='user.Dormitory')),
            ],
        ),
        migrations.AddField(
            model_name='dormitory',
            name='repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Repair'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_num', models.CharField(max_length=20)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_sex', models.BooleanField(default=0)),
                ('emp_age', models.IntegerField()),
                ('quhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Dormitory')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='dormitory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Dormitory'),
        ),
    ]
