# Generated by Django 2.2.1 on 2021-07-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210701_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='quhao',
        ),
        migrations.RemoveField(
            model_name='dormitory',
            name='repair',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dormitory',
        ),
        migrations.CreateModel(
            name='Waijian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Admin')),
                ('dormitory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Dormitory')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Pay')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Repair')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student')),
            ],
        ),
    ]
