# Generated by Django 2.2.1 on 2021-07-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210701_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='sushe_num',
        ),
        migrations.AddField(
            model_name='repair',
            name='sushe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='repair',
            name='data',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='sintime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='souttime',
            field=models.CharField(max_length=20),
        ),
    ]
